In [6]:
import numpy as np

arr = np.random.randn(3, 3)

print(arr)
print(arr+arr)
print(arr-arr)
print(arr*arr)
print(arr/arr)
print(arr%arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)


[[ 0.33221609 -0.0668674   0.73806527]
 [ 0.19792613 -0.83089097  0.03069355]
 [ 1.52339949  2.16639265 -1.11291377]]
[[ 0.66443217 -0.13373481  1.47613054]
 [ 0.39585226 -1.66178195  0.06138709]
 [ 3.04679898  4.33278529 -2.22582754]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.10367528e-01 4.47124972e-03 5.44740344e-01]
 [3.91747539e-02 6.90379811e-01 9.42093749e-04]
 [2.32074601e+00 4.69325710e+00 1.23857706e+00]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0. -0.  0.]
 [ 0. -0.  0.]
 [ 0.  0. -0.]]
2
(3, 3)
float64


In [22]:
print(np.arange(9))
print(np.ones((3,3)))
print(np.zeros((3,3)))
print(np.empty((3,3)))
print(np.eye(3,3))
print(np.identity(3))


[0 1 2 3 4 5 6 7 8]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
arr2 = np.random.randn(3,3)
arr3 = np.random.randn(3,3)

print(arr2>arr3)
print(arr2>=arr3)
print(arr2==arr3)
print(arr2<=arr3)
print(arr2<arr3)
print(arr2!=arr3)

[[False  True False]
 [ True False  True]
 [False  True False]]
[[False  True False]
 [ True False  True]
 [False  True False]]
[[False False False]
 [False False False]
 [False False False]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''